### PR TITLE
Update docs for version 2.4.0

### PR DESCRIPTION
**Pull request by rishikeshpalve**
Please review and merge the pull request to update the docs for v2.4.0 release.

### CODE REVIEW

**Comment by jknostman3** [comment]
@rishikeshpalve Thanks!

**Comment by jncd** [comment]
Hello @rishikeshpalve 

I noticed that you changed "TIBCO Business Studio for BusinessWorks development environment" to 
"TIBCO Business Studio Container Edition development environment" in the PR but I see other examples of "TIBCO Business Studio Container Edition development environment" in the doc. 
You might want to review all the TIBCO product names in this doc, just to protect your branding.

**Comment by rishikeshpalve** [comment]
Thanks @jncd for pointing it out. @kgera-tibco is fixing it in the new PR we have created for version 2.4.3 release.

**Comment by kgera-tibco** [comment]
@jncd : I've made the changes under a file and now we refer to component everywhere as: **TIBCO Business Studio for BusinessWorks**.
Please let me know if any further action seems to be missing from my end.
cc @rishikeshpalve

**Comment by jncd** [comment]
Thanks @rishikeshpalve  and @kgera-tibco

**Pull request merged**
